### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [vjujjavarapu/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

         - [ ] Your name
         - [ ] Where you are from
         - [ ] A favorite food
         - [ ] A hobby

**Comment by vjujjavarapu** [comment]
- venkatesh jujjavarapu
- edison, new jersey
- chicken hakka noodles
- create my own acoustic version and sing almost every sone while driving.
